name: Bit export CI

on:
  release:
    types: [published]

jobs:
  bit-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
         token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2
        with:
         node-version: '14.x'
      - run: git checkout master

      # Install dependencies and build app
      - name: Install Dependencies
        run: npm install
      - name: Install bit-bin
        run: npm install bit-bin --global  
      - name: bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
          bit config
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: bit import
        run: |
          bit -v
          bit import totalsoft_oss.react-mui/accordion totalsoft_oss.react-mui/upload-button totalsoft_oss.react-mui/card totalsoft_oss.react-mui/card-title totalsoft_oss.react-mui/chart-card totalsoft_oss.react-mui/charts totalsoft_oss.react-mui/custom-dialog totalsoft_oss.react-mui/custom-linear-progress totalsoft_oss.react-mui/upward-button totalsoft_oss.react-mui/date-time totalsoft_oss.react-mui/dialog-display totalsoft_oss.react-mui/dynamic-input totalsoft_oss.react-mui/file-upload-button totalsoft_oss.react-mui/image-card totalsoft_oss.react-mui/add-button totalsoft_oss.react-mui/not-found totalsoft_oss.react-mui/password-field totalsoft_oss.react-mui/pagination totalsoft_oss.react-mui/regular-card totalsoft_oss.react-mui/side-menu totalsoft_oss.react-mui/simple-slider totalsoft_oss.react-mui/stats-card totalsoft_oss.react-mui/toast totalsoft_oss.react-mui/template-editor totalsoft_oss.react-mui/fake-text totalsoft_oss.react-mui/expanding-text totalsoft_oss.react-mui/custom-linear-progress totalsoft_oss.react-mui/default-logo totalsoft_oss.react-mui/typography totalsoft_oss.react-mui/cancel-button totalsoft_oss.react-mui/back-to-button totalsoft_oss.react-mui/themes/blue-theme totalsoft_oss.react-mui/themes/red-theme totalsoft_oss.react-mui/themes/green-theme totalsoft_oss.react-mui/themes/orange-theme totalsoft_oss.react-mui/themes/default-theme --override
          bit import
          bit build
      - name: Run tests
        run: npm run test:ci
      - name: bit export
        run: |
          bit status
          bit tag --scope ${{ env.RELEASE_VERSION }}
          bit export
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Updated bitmap file
