name: Bit export CI

on:
  release:
    types: [published]

jobs:
  bit-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
         token: ${{ secrets.PAT }}
      - run: git checkout master

      # Install dependencies and build app
      - name: Install Dependencies
        run: npm install
      - name: Install bit-bin
        run: npm install bit-bin --global  
      - name: bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
          bit config
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: bit import
        run: |
          bit -v
          bit import totalsoft_oss.react-mui/cancel-button totalsoft_oss.react-mui/card-title totalsoft_oss.react-mui/card totalsoft_oss.react-mui/charts totalsoft_oss.react-mui/check-internet-connection totalsoft_oss.react-mui/constants totalsoft_oss.react-mui/custom-dialog totalsoft_oss.react-mui/custom-linear-progress totalsoft_oss.react-mui/custom-text-field --override
          bit import
          bit build
      - name: Run tests
        run: npm run test:ci
      - name: bit export
        run: |
          bit status
          bit tag --scope ${{ env.RELEASE_VERSION }}
          bit export
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Updated bitmap file
